import type { ViralTitlePreset } from "./types";

/**
 * Original PronixCut looks for word-highlighted captions, inspired by the
 * general shape of professional short-form caption styles (bold text, one
 * highlighted word at a time, punchy per-word motion) — no third-party
 * template, asset, or exact styling is copied.
 */
export const BUILTIN_VIRAL_TITLE_PRESETS: ViralTitlePreset[] = [
	{
		id: "impacto",
		name: "Impacto",
		values: {
			fontFamily: "Arial",
			fontWeight: "bold",
			fontSize: 22,
			color: "#ffffff",
			"stroke.enabled": true,
			"stroke.color": "#000000",
			"stroke.width": 8,
			"wordHighlight.enabled": true,
			"wordHighlight.activeColor": "#FFC600",
			"wordHighlight.animation": "pop",
			"wordHighlight.activeScale": 1.12,
			"wordHighlight.background": false,
			"wordHighlight.maxWordsPerLine": 3,
			"wordHighlight.uppercase": true,
		},
	},
	{
		id: "punch",
		name: "Punch",
		values: {
			fontFamily: "Arial",
			fontWeight: "bold",
			fontSize: 20,
			color: "#ffffff",
			"stroke.enabled": false,
			"wordHighlight.enabled": true,
			"wordHighlight.activeColor": "#ffffff",
			"wordHighlight.animation": "punch",
			"wordHighlight.activeScale": 1.3,
			"wordHighlight.background": false,
			"wordHighlight.maxWordsPerLine": 4,
			"wordHighlight.uppercase": false,
		},
	},
	{
		id: "clean",
		name: "Clean",
		values: {
			fontFamily: "Arial",
			fontWeight: "normal",
			fontSize: 18,
			color: "#ffffff",
			"stroke.enabled": false,
			"wordHighlight.enabled": true,
			"wordHighlight.activeColor": "#FFC600",
			"wordHighlight.animation": "none",
			"wordHighlight.activeScale": 1,
			"wordHighlight.background": false,
			"wordHighlight.maxWordsPerLine": 6,
			"wordHighlight.uppercase": false,
		},
	},
	{
		id: "box",
		name: "Box",
		values: {
			fontFamily: "Arial",
			fontWeight: "bold",
			fontSize: 18,
			color: "#ffffff",
			"stroke.enabled": false,
			"wordHighlight.enabled": true,
			"wordHighlight.activeColor": "#ffffff",
			"wordHighlight.animation": "pop",
			"wordHighlight.activeScale": 1.05,
			"wordHighlight.background": true,
			"wordHighlight.backgroundColor": "#111214",
			"wordHighlight.maxWordsPerLine": 4,
			"wordHighlight.uppercase": false,
		},
	},
	{
		id: "yellow-focus",
		name: "Yellow Focus",
		values: {
			fontFamily: "Arial",
			fontWeight: "bold",
			fontSize: 20,
			color: "#ffffff",
			"stroke.enabled": true,
			"stroke.color": "#000000",
			"stroke.width": 4,
			"wordHighlight.enabled": true,
			"wordHighlight.activeColor": "#FFC600",
			"wordHighlight.animation": "bounce",
			"wordHighlight.activeScale": 1.15,
			"wordHighlight.background": false,
			"wordHighlight.maxWordsPerLine": 4,
			"wordHighlight.uppercase": false,
		},
	},
	{
		id: "pop",
		name: "Pop",
		values: {
			fontFamily: "Arial",
			fontWeight: "bold",
			fontSize: 20,
			color: "#ffffff",
			"stroke.enabled": false,
			"wordHighlight.enabled": true,
			"wordHighlight.activeColor": "#FFC600",
			"wordHighlight.animation": "pop",
			"wordHighlight.activeScale": 1.25,
			"wordHighlight.background": false,
			"wordHighlight.maxWordsPerLine": 3,
			"wordHighlight.uppercase": false,
		},
	},
	{
		id: "editorial",
		name: "Editorial",
		values: {
			fontFamily: "Arial",
			fontWeight: "bold",
			fontSize: 17,
			color: "#ffffff",
			letterSpacing: 0.5,
			"stroke.enabled": false,
			"wordHighlight.enabled": true,
			"wordHighlight.activeColor": "#ffffff",
			"wordHighlight.animation": "none",
			"wordHighlight.activeScale": 1,
			"wordHighlight.background": false,
			"wordHighlight.maxWordsPerLine": 6,
			"wordHighlight.uppercase": true,
		},
	},
	{
		id: "headline",
		name: "Headline",
		values: {
			fontFamily: "Arial",
			fontWeight: "bold",
			fontSize: 26,
			color: "#ffffff",
			"stroke.enabled": true,
			"stroke.color": "#000000",
			"stroke.width": 6,
			"wordHighlight.enabled": true,
			"wordHighlight.activeColor": "#FFC600",
			"wordHighlight.animation": "pop",
			"wordHighlight.activeScale": 1.1,
			"wordHighlight.background": false,
			"wordHighlight.maxWordsPerLine": 2,
			"wordHighlight.uppercase": true,
		},
	},
];
